### PR TITLE
Evalute expected result in Test::Deep namespace

### PR DESCRIPTION
**Pull request by andreifyodorov**

### CODE REVIEW

**Comment by mkllnk** [comment]
Yes, I think that is a lot better. _But_, the original author wrote the script without any non-core dependencies. Which dependencies did we add?
- `Module::Metadata` is quite useful to determine the package and run the code within that package. I'm not sure if there is a better solution.
- `Test::Deep` enables you to write more sophisticated tests. But I would think that most users would be happy with `is_deeply` from `Test::More`. If you want to use `bag`, you can do that in your comment.

``` pod
>>> use Test::Deep 'bag';
>>> bag(my_numbers());
bag([1, 2, 3])
```

Yes, that adds overhead if you want to use `bag`, but I think that most users don't use it. And there are probably a lot more handy test libraries someone would like to use without declaring the dependency. Who is in and who is out?

And another problem of this syntax is that people don't know where this `bag` method comes from. You need to look into the code to find that out. And it doesn't work if the module to test contains another sub called `bag`.

I would prefer to keep the dependencies small and follow the principle: _better to do one thing right, than a lot of things mostly right_

Okay, that was my opinion. What do you think?

**Comment by andreifyodorov** [comment]
1. I don't see any problems with adding more dependencies, especially to modules such as Test::Deep
   a. it's widely used https://metacpan.org/requires/distribution/Test-Deep
   b. it's mentioned in perldoc http://perldoc.perl.org/Test/More.html#Complex-data-structures
2. Practical experience tells me that it's an absolute must-have when you start to deal with more complicated cases, like method testing. Consider a real life example:
   
   ```
   =begin get_metrics
   
   >>> [__PACKAGE__->retrieve(51)->get_metrics]
   noclass(bag(
       superhashof({metric_id => superhashof({name => 'pricing_score'})}),
       superhashof({metric_id => superhashof({name => 'availability_score'})}),
       superhashof({metric_id => superhashof({name => 'content_score'})}),
       superhashof({metric_id => superhashof({name => 'extra_score'})}),
   ))
   
   =cut
   ```
3. The way you propose to implement this is not possible
   a. Expected values are evaluated in different namespace than test code. I believe that's the right approach, they should be separated at least to the certain extent. Otherwise it would be possible to write something correct, but pointless, like that:
   
   ```
     >>> my_numbers()
     my_numbers()
   
   ```
   
   b. So, if to abolish the dependency of Test::Deep, we'd have to write something like
   
   ```
     >>> use Test::Deep;
     >>> my_numbers()
     Test::Deep::bag(1, 2, 3)
   ```
   
   which is no better than it was. 
   c. Or to invent some special syntax to change namespace, like
   
   ```
     >>> Test::Doctest::set_expected_namespace('Test::Deep')
     >>> my_numbers()
     bag(1, 2, 3)
   ```
4. I can't see any candidates other than Test::Deep for a namespace for evaluating expected results. In case somebody needs functionality it lacks, I'd propose to contribute directly to it.

**Comment by andreifyodorov** [comment]
Actually, no, 3c won't work.
Expected result prepared with Test::Deep helpers like `bag`, `superhashof` and so on, can only be compared with Test::Deep's `cmp_deeply`.
So it's either always Test::Deep or never.

**Comment by mkllnk** [comment]
Thanks a lot for your reply. It makes a lot of sense. The fact that `bag` and others don't work without `cmp_deeply` makes it difficult to find a better, more flexible solution.

One option could be that you can define your own compare method. But since there is nobody complaining about `Test::Deep` or requesting another compare method at the moment, I wouldn't bother.

**Pull request merged**
