### PR TITLE
Change perltidy parameters

### PR DESCRIPTION
**Pull request by andreifyodorov**
Hi, I propose some changes in perltidy parameters

### CODE REVIEW

**Comment by mkllnk** [comment]
Can you explain the reasons for each parameter?

I assumed that the default set is the most commonly used and therefore the most clear for most Perl developers. But I might be wrong. Since I'm more used to styles used in Java, PHP, Javascript, Python, Ruby and others, there are some settings that are not as intuitive for me. But I'm probably not the average Perl developer.

Do you know which set is used by the Perl core code?

**Comment by andreifyodorov** [comment]
It's mostly about eliminating extra spaces inside brackets, as you can see in diff
There's no such thing as PEP8 in perl world, and "perlstyle" is very general, so it's up to every developer to decide on his own

http://perldoc.perl.org/perlstyle.html

**Comment by mkllnk** [comment]
I was wondering if you came up with this configuration, because you prefer it this way, or if you copied it from somewhere else.

Now, I did the work myself to go through `man perltidy`, lookup the effect and then test with our code base to see what it means to our code in the real world. Based on the effects on our code, styles I have seen in other modules and my personal way of looking at things, I have an opinion on these parameters now.

Okay, let's go through.
- `--maximum-line-length=100` I do prefer the default of `80`. In this example, it effects only one line.

``` perl
             my $outof = $#$group > 0 ? sprintf("%d/%d", $i + 1, $#$group + 1) : q();
```

I think, this example shows that lines longer than 80 characters are often too complex and should be rewritten for readability. And then the code is more portable to show on different websites, in emails etc.
- `--paren-tightness=2` which means `($a, $b)` instead of `( $a, $b )`. I agree. That's standard in most popular languages and a lot of popular perl modules.
- `--square-bracket-tightness=2` Similar `[0, 1]`. I agree. That's standard in most popular languages and a lot of popular perl modules.
- `--brace-tightness=2` Same for `$obj->{$array_ref->[0]}` I agree. Even though I prefer to keep the content of the braces so simple that the default level of `1` doesn't introduce spaces either.
- `--block-brace-tightness=1` I don't agree. It creates this odd situation in which some blocks have spaces and some don't. That is one more reason why I don't like the default values of the settings listed above. Just from my point of view, I'm not hundred percent sure if I would prefer `0` or `2`. But in doubt I would go with the default which is kind of a standard. It makes the difference between normal braces and block braces more clear as well.
- `--noblanks-before-comments` I quite like the blank lines. Often I would even say: It would be better to make the code so clear that it doesn't need a comment any more, for example by introducing a sub with a good name.
- `--break-at-old-comma-breakpoints` I see the point. This enables the author to make the code clearer then perltidy would do it. I agree.

Last, but not least. If I run perltidy, I get a different output that look a bit like a bug:

``` perl
package Test::Doctest::Builder {
    use Test::Deep::NoTest qw(cmp_details deep_diag);

      use base 'Test::Builder'; # <--- Why is there another indent?

      our $Test;
      sub new { $Test ||= shift->create }

    sub is_eq {
        my $self = shift;
        my ($got, $expected, $test_name) = @_;
        if (ref $expected) {
            my ($ok, $stack) = cmp_details($got, $expected);
            $self->diag(deep_diag($stack)) unless $self->ok($ok, $test_name);
            return;
        }
        $self->SUPER::is_eq(@_);
    }
  }

  our ($Result, $Check); # <--- And here as well.

```

Does that happen on your system as well? I use perltidy version v20101217.

**Comment by andreifyodorov** [comment]
Yes, that is configuration that I came up with on my own, and it reflects my idea about what readable code is.

Ok, let's change --block-brace-tightness to default.

Without --noblanks-before-comments it leads to inserting weird new-lines before comments, that breaks the logic of grouping statements together. So I propose to keep it.

As for the last question, yes, that should be a bug in your version of perltidy, try updating it.

**Comment by andreifyodorov** [comment]
I also removed --maximum-line-length=100

**Comment by mkllnk** [comment]
Thank you.

**Pull request merged**
