### PR TITLE
Add package files

### PR DESCRIPTION
**Pull request by andreifyodorov**

### CODE REVIEW

**Comment by mkllnk** [comment]
Cool. Thanks. Do you have an idea what to do about the duplicate content?
- .gitignore and ignore.txt
- Changes and end of Doctest.pm
- README and README.md
- README and Doctest.pm

**Comment by andreifyodorov** [comment]
.gitignore and ignore.txt are slightly different, ignore.txt also ignores files that don't go into dist
about others, well, nothing so far as they can be maintained manually since releases are not that often

**Comment by mkllnk** [comment]
I'm wondering if there is a dependency missing.

``` sh
make
# Checking if your kit is complete...
# Looks good
# Writing Makefile for Test::Doctest
# Writing MYMETA.yml
make test
# PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
# t/Doctest.t .. Can't locate Test/Deep/NoTest.pm in @INC (@INC contains: /home/maikel/github/PerlDoctest/blib/lib /home/maikel/github/PerlDoctest/blib/arch lib lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /home/maikel/github/PerlDoctest/blib/lib/Test/Doctest.pm line 279.
# BEGIN failed--compilation aborted at /home/maikel/github/PerlDoctest/blib/lib/Test/Doctest.pm line 279.
# Compilation failed in require at t/Doctest.t line 8.
# BEGIN failed--compilation aborted at t/Doctest.t line 8.
# t/Doctest.t .. Dubious, test returned 2 (wstat 512, 0x200)
# No subtests run 
# 
# Test Summary Report
# -------------------
# t/Doctest.t (Wstat: 512 Tests: 0 Failed: 0)
#   Non-zero exit status: 2
#   Parse errors: No plan found in TAP output
# Files=1, Tests=0,  0 wallclock secs ( 0.04 usr  0.00 sys +  0.05 cusr  0.02 csys =  0.11 CPU)
# Result: FAIL
# Failed 1/1 test programs. 0/0 subtests failed.
# make: *** [test_dynamic] Error 2
```

**Comment by mkllnk** [comment]
When is ignore.txt used? Could we generate it with Makefile.PL?

**Comment by andreifyodorov** [comment]
ignore.txt is not used actually, files for dist are taken from MANIFEST, so I removed ignore.txt
also added Test::Deep dependency

**Comment by mkllnk** [comment]
Good. Do you know what the CHANGES files does? Should it be more detailed than the HISTORY part of the module's pod?

**Comment by andreifyodorov** [comment]
CHANGES is just a text file, that is usually there, like README

**Comment by mkllnk** [comment]
I had a look into `man perlnewmod` and it suggests to look into some well known packages like Text::Tabs, File::Copy and WWW::Mechanize. None of them have the version history in the pod. But they have a file called `Changes`.

And I found a possible solution for the readme problem: http://stackoverflow.com/questions/13188404/how-to-make-my-perl-modules-readme-file-compatible-with-githubs-markdown-displ
It suggests to have a `README.pod` file that should be accepted by GitHub and by Perl tools. What do you think about that?

**Pull request merged**
