### PR TITLE
Further development

### PR DESCRIPTION
**Pull request by andreifyodorov**
I was practically using this module for about half a year, and made some changes during that time

### CODE REVIEW

**Comment by mkllnk** [comment]
This looks all pretty good. Thank you. I didn't have time to test it myself yet. And I normally use `perltidy` for consistent styling. What do you think about that?
I noticed that you prefer tabs over spaces...

**Comment by andreifyodorov** [comment]
I actually prefer 4 spaces, and it was 2 spaces originally, so I changed it to tabs, because it is something everyone can setup the way one likes...

what do you think about putting this module to CPAN?

**Comment by mkllnk** [comment]
I prefer 4 spaces as well. But I didn't write the module. I just copied it from http://blog.crdlo.com/2010/04/doctests-for-perl.html.

I think it's a great idea to put this module on CPAN. Is that something you would like to do?

**Comment by andreifyodorov** [comment]
I never did the CPAN thing before, but yes, I'd like this module to be there, so I'll investigate that.

**Comment by andreifyodorov** [comment]
Thank you!

**Pull request merged**
